global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'json-auth-service'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets: ['thundering-kellie-rafasya-org-60e1472c.koyeb.app']