spring.application.name=json-auth-service
server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=JsonWarTiketDanBarangLimitedEditionB9SecretKey2026RahasiaLokal

app.wallet-service.base-url=${WALLET_SERVICE_URL:http://localhost:8082}
app.order-service.base-url=${ORDER_SERVICE_URL:http://localhost:8084}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true